[package]
name = "sentinel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "sentinel"
path = "src/main.rs"

[dependencies]
serde = {version = "1.0.228", features = ["derive"] }
toml = "1.0.0"
daemonize = "0.5"
chrono = "0.4"
dirs = "6.0.0"
